### ISSUE TITLE
Promote Reshama's keynote at PyData Berlin

### ISSUE THREAD

**Issue by laurburke** [scikit-learn/communication#18]
https://2022.pycon.de/blog/keynote-2-reshama-shaikh
![keynote-reshama](https://user-images.githubusercontent.com/35973528/162487882-2f5830bc-7160-4f2b-87b4-54f868a6946e.png)
/

**Comment by glemaitre** [comment]
The videos are now online and could be added to the YouTube playlist:

https://www.youtube.com/watch?v=V03NkNGEF3w&list=PLGVZCDnMOq0p0Fal8_YKg6fPXnf3iPtwD&index=15&ab_channel=PyData (tutorial)

**Comment by ogrisel** [comment]
The video of the keynote has been included in the blog post:

https://blog.scikit-learn.org/events/pyconde-keynote-reshama/
