### ISSUE TITLE
1.1 Release

### ISSUE THREAD

**Issue by francoisgoupil** [scikit-learn/communication#20]
For information, Thomas started to draft some release highlights for 1.1 in https://github.com/scikit-learn/scikit-learn/pull/23084.

Here is the HTML rendering of the current state of the PR : https://output.circle-artifacts.com/output/job/d83a2974-e9d4-479b-814d-46bb0fa99489/artifacts/0/doc/auto_examples/release_highlights/plot_release_highlights_1_1_0.html

**Comment by jeremiedbb** [comment]
The first release candidate is out for the 1.1.0 release. ``pip install scikit-learn==1.1.0rc1``.
It would be nice to annouce it on twitter so that people can start testing it and give feedback or report regression before we make the final release.

**Comment by francoisgoupil** [comment]
Done. Thanks @jeremiedbb !

**Comment by jeremiedbb** [comment]
The final release is out
