### ISSUE TITLE
Branding Guidelines

### ISSUE THREAD

**Issue by laurburke** [scikit-learn/communication#28]
How to communicate about scikit-learn. 

Will include information on:
- Logos
- Brand colors
- Background info
- How/when you can use the scikit-learn brand

**Comment by laurburke** [comment]
Summary: https://www.bynder.com/en/glossary/brand-guidelines-definition/#:~:text=Brand%20guidelines%20are%20clearly%20defined,and%20what%20it%20stands%20for.

Examples
- https://www.datavisualizationsociety.org/brand-guidelines

**Comment by reshamas** [comment]
@laurburke 
As an FYI, I set this up recently; new info can be added:
https://github.com/scikit-learn/scikit-learn/blob/main/doc/logos/README.md

**Comment by laurburke** [comment]
@reshamas Okay perfect! I was going to add more about logo placement, backgrounds, etc. I will submit a PR to that page once I have something more.
