### ISSUE TITLE
share swag store on social media

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/communication#30]
scikit-learn swag options are up, added by NumFOCUS:
https://numfocus.myspreadshop.com/all

https://numfocus.myspreadshop.com/scikit-learn+logo?idea=6335cad48f3f5268f5f42559

**Comment by laurburke** [comment]
I’ll get this queued today!

**Comment by GaelVaroquaux** [comment]
Thanks to all of you, this is super cool!!
