### ISSUE TITLE
Update social media header and logo pictures

### ISSUE THREAD

**Issue by francoisgoupil** [scikit-learn/communication#32]
I noticed that for instance the scikit-learn logo of our twitter account is not the right one. 
Also, we may want to change the cover banner of this account. 

![twitter logo](https://user-images.githubusercontent.com/98105626/196419425-ed06614a-2f28-42fe-b28f-05c2fe880bbf.png)
![twitter-account](https://user-images.githubusercontent.com/98105626/196419431-f7a2aec8-41cb-411f-aff5-3c5f83f4f751.png)

**Comment by francoisgoupil** [comment]
Note: I don't have access to the admin interface I only have posting rights through tweetdeck.

**Comment by laurburke** [comment]
@francoisgoupil What would you suggest as a cover banner? We added this image last year because it was previously empty. I can design an element if you have suggestions for the content!

**Comment by laurburke** [comment]
The Twitter logo has been updated. Some social media accounts will show a black/gray background for profile images with a transparent background. Here is the image I used, where I centered it on a white background. 
![scikit-learn-logo-white-square](https://user-images.githubusercontent.com/35973528/204357173-acb1e31b-1ad6-434b-b0c0-9fa99b2f9984.png)
