### ISSUE TITLE
Creating a Mastodon account

### ISSUE THREAD

**Issue by francoisgoupil** [scikit-learn/communication#33]
Given the recent news and the philosophy of Mastodon. We discussed the possibility of creating a Mastodon account for scikit-learn with @ogrisel. What do you think about it?

**Comment by ogrisel** [comment]
If we do, we will have to choose which server to use. Each server might have different moderation rules and hosting stability guarantees.

**Comment by francoisgoupil** [comment]
The [Fosstodon](https://fosstodon.org/about) server could be a suitable one. It is one recommended by Mastodon as "consistently committed to moderation against racism, sexism, and transphobia" and is dedicated to open source software.

**Comment by ogrisel** [comment]
Yes the fosstodon server sounds good. 

The details about the server admin:

- https://fosstodon.org/about/more

Note that it's an English-only server but this is fine for the scikit-learn account I think.

**Comment by ogrisel** [comment]
A bit of background of the load increase on fosstodon:

- https://hub.fosstodon.org/elon-twitter-post-mortem/

After the upgrade, it seems to be operating well again. If we locate the scikit-learn account there we should try to see if we could do a small regular donation to help with the hosting fees (e.g. from the numfocus account?).

**Comment by francoisgoupil** [comment]
I created an account, waiting to be reviewed by Fosstodon maintainers.
![pending_review_fosstodon](https://user-images.githubusercontent.com/98105626/204822549-0ffd337a-a7ac-44d7-aa68-93b138fc4b28.png)

**Comment by francoisgoupil** [comment]
It is accessible on here: https://fosstodon.org/@sklearn

**Comment by GaelVaroquaux** [comment]
> It is accessible on here: ***@***.***

Awesome!! Great job!
