### ISSUE TITLE
No test scores when using Pipeline in GridSearchCV

### ISSUE THREAD

**Issue by guanjingyu** [scikit-learn/communication#39]
```
mix_params = {
    'onehot__max_categories': [3, 6, 9, 12],
    'rf__n_estimators': [10, 20],
    'rf__max_depth': [2, 5],
    'rf__min_samples_split': [2, 5],
    'rf__min_samples_leaf': [2, 5],
    'rf__max_features': ['auto', 'sqrt', 'log2', None],
    'rf__bootstrap': [True, False]
}

pipe = Pipeline([
    ('onehot', OneHotEncoder(sparse_output=False)),
    ('rf', RandomForestClassifier(random_state=42))
])

model = GridSearchCV(pipe,
                     param_grid=mix_params,
                     scoring=['roc_auc', 'accuracy', 'recall', 'precision'],  
                     refit='accuracy',
                     return_train_score=True,
                     cv=5, n_jobs=1)

model.fit(X, y)

model.cv_results_['mean_test_accuracy']
```

In this case, a Pipeline is used in GridSearchCV. but  ``model.best_score_`` and ``model.best_index_`` are nan and 0, which means all testing scores are NaN, is anyone know how is this happening and how to fix?

**Comment by GaelVaroquaux** [comment]
Hello,

This is not the right place to report bugs with scikit-learn, as this is a repository to synchronize official communication on scikit-learn. I am closing the issue.

With regard to your specific problem, if you want to ask for help, you will need to share the data, as it is impossible to reproduce the problem without it.

Best

**Comment by reshamas** [comment]
@guanjingyu 
Here is more info on where you can ask questions:
https://scikit-learn.org/stable/support.html#bug-tracker
