### ISSUE TITLE
social media post request: Julien's performance blogs

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/communication#5]
https://blog.scikit-learn.org/performance/performances/

cc:  @laurburke @jjerphan @francoisgoupil

**Comment by jjerphan** [comment]
@reshamas: I can, but I do not have any inspirations. I would have done a UML diagram to describe the design of the core from a bird eyes view, but I am not sure this practice makes unanimity in the team.

**Comment by jjerphan** [comment]
@reshamas: I do not have any strong inspirations yet, I think this can be posted without any image.

**Comment by reshamas** [comment]
@laurburke what do you think of having a design for a generic blog social media card to use on Buffer?

**Comment by laurburke** [comment]
@reshamas I think that's a good idea! If you have specific ideas, I can design one.

**Comment by reshamas** [comment]
@laurburke I had a bunch of blogs on Data Umbrella w/o social media cards so I created this:
https://blog.dataumbrella.org/tags/#sprint-blog

For @jjerphan , could add the title of the blog.  if there's some applicable icon for "performance", clock, stopwatch, etc, we could add that.
- and could add scikit-learn logo too.

**Comment by laurburke** [comment]
@reshamas If we wanted to, I could make both a generic design and a basic template (with an editable post title, and available via Canva).

Then individuals could choose to use either the generic image or the template. With the template, they would just need to update the title, download the card, and add it to Github themselves. Idk if this is too complicated, but we could have it available as an option.

**Comment by reshamas** [comment]
@laurburke sounds good to me.

**Comment by reshamas** [comment]
@laurburke I created a temporary social media card.  We can replace it with a prettier image when it's ready.

@jjerphan 
The post has been shared on LinkedIn, Twitter and FB.

**Comment by jjerphan** [comment]
Thank you, @reshamas and @laurburke.
