### ISSUE TITLE
YouTube: custom URL

### ISSUE THREAD

**Issue by reshamas** [scikit-learn/communication#6]
Now that we have 100+ subscribers on YouTube, we can set up a custom URL:
https://www.youtube.com/channel/UCJosFjYm0ZYVUARxuOZqnnw

cc:  @laurburke

**Comment by laurburke** [comment]
Our custom URL is: [https://www.youtube.com/c/scikitlearnofficial](https://www.youtube.com/c/scikitlearnofficial). It required that I add additional chars/numbers so I added the "official". We may be able to submit a request to YouTube to change it to just "scikitlearn" in the future.
