### ISSUE TITLE
PyConDE & PyData Berlin 2022

### ISSUE THREAD

**Issue by glemaitre** [scikit-learn/communication#9]
I am going to make a tutorial at the upcoming PyData Berlin: https://2022.pycon.de/program/9LZTRR/

I can provide any further information if required (I still need to prepare the talk thought :))

**Comment by laurburke** [comment]
@glemaitre Did they provide you with a promo image for social media? If you have one, that would be great to share along with this news!

**Comment by glemaitre** [comment]
Yes. The following:

![image](https://user-images.githubusercontent.com/7454015/162484057-52e0e9ff-f05e-4bfe-bde3-fa29ef2efd26.png)

But there is a typo in the title :)

I quickly changed some slides that I used in PyLadies last Tuesday and adapt them slightly:

https://docs.google.com/presentation/d/1xPf8vN9-pwZkAq28gbghJ9IWaNO4w-ZKO59193BWs34/edit?usp=sharing

Feel free to use this visual if you think it is better to not have the typo in the first verb

**Comment by laurburke** [comment]
Not a problem! This will work great, and I can just put an overlay over top of it to fix the typo.

**Comment by glemaitre** [comment]
Here I am adding the link to the video that was posted on YouTube:

https://www.youtube.com/watch?v=V03NkNGEF3w&list=PLGVZCDnMOq0p0Fal8_YKg6fPXnf3iPtwD&index=15&ab_channel=PyData

**Comment by francoisgoupil** [comment]
Thanks @glemaitre I added it to the Youtube playlist there https://www.youtube.com/playlist?list=PLM-1QqX7UksRycJ-AtFRHilcTl34FdA9j
